steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/fraudfinderdemo/hugo:0.1', './CICD' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/fraudfinderdemo/hugo:0.1']
- name: 'gcr.io/fraudfinderdemo/hugo:0.1'
  dir: './fraudfinder'
  id: 'Build Hugo'
- name: 'gcr.io/fraudfinderdemo/hugo:0.1'
  dir: './fraudfinder'
  args: ['deploy']
  id: 'Deploy into GCS'
  waitFor: ['Build Hugo']