baseURL = 'http://www.fraudfinder-workshop.com/'
languageCode = 'en-us'
title = 'Fraud Finder Workshop'
theme = "hugo-theme-learn"
[params]
  themeVariant = "mine"

[[deployment.targets]]
# An arbitrary name for this target.
name = "www.fraudfinder-workshop.com"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://www.fraudfinder-workshop.com"